"""empty message

Revision ID: 00ef3d5546b2
Revises: 3dc4b9e1fc82
Create Date: 2024-02-04 12:51:50.396492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ef3d5546b2'
down_revision = '3dc4b9e1fc82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.drop_column('services')

    # ### end Alembic commands ###
