"""empty message

Revision ID: 22138ace508e
Revises: 2e654a15a3c1
Create Date: 2024-02-05 11:32:15.297462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22138ace508e'
down_revision = '2e654a15a3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))

    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('laboratory', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
