"""empty message

Revision ID: 2e654a15a3c1
Revises: 
Create Date: 2024-02-05 06:05:01.805600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e654a15a3c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('employee', sa.Integer(), nullable=True),
    sa.Column('year_founded', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('sex', sa.Enum('not_given', 'male', 'female', 'non_binary', name='sex'), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('affiliate_id', sa.String(length=10), nullable=True),
    sa.Column('affiliated_by', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('verify', sa.DateTime(), nullable=True),
    sa.Column('verify_by_admin', sa.Boolean(), nullable=True),
    sa.Column('blood_type', sa.Enum('Not_given', 'A_positive', 'A_negative', 'B_positive', 'B_negative', 'O_positive', 'O_negative', 'AB_positive', 'AB_negative', name='bloodtype'), nullable=True),
    sa.Column('user_type', sa.Enum('normal', 'doctor', name='usertype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('laboratory_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laboratory_id', sa.String(length=36), nullable=False),
    sa.Column('branch_name', sa.String(length=256), nullable=True),
    sa.Column('manager', sa.String(length=256), nullable=False),
    sa.Column('services', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratory.id'], name='fk_laboratory_branch_to_laboratory'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_UserAddress_to_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laboratory_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_branch_id', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['lab_branch_id'], ['laboratory_branch.id'], name='fk_address_to_laboratory_branch'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_branch_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laboratory_address')
    op.drop_table('user_address')
    op.drop_table('laboratory_branch')
    op.drop_table('users')
    op.drop_table('laboratory')
    # ### end Alembic commands ###
