"""empty message

Revision ID: 3dc4b9e1fc82
Revises: 905f588641b1
Create Date: 2024-02-04 12:45:09.712785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc4b9e1fc82'
down_revision = '905f588641b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manager', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratory_branch', schema=None) as batch_op:
        batch_op.drop_column('manager')

    # ### end Alembic commands ###
