"""empty message

Revision ID: 4f1a9e402730
Revises: 20b110a1b4ad
Create Date: 2024-02-03 20:02:14.498827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1a9e402730'
down_revision = '20b110a1b4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.Enum('Not_given', 'A_positive', 'A_negative', 'B_positive', 'B_negative', 'O_positive', 'O_negative', 'AB_positive', 'AB_negative', name='bloodtype'), nullable=True))
        batch_op.add_column(sa.Column('type', sa.Enum('normal', 'doctor', name='type'), nullable=True))
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=11), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('blood_type')

    # ### end Alembic commands ###
