"""empty message

Revision ID: 61aef44f05e6
Revises: 4f1a9e402730
Create Date: 2024-02-04 06:45:55.375649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61aef44f05e6'
down_revision = '4f1a9e402730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sex', sa.Enum(), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.Enum('normal', 'doctor', name='usertype'), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=6), nullable=True))
        batch_op.drop_column('user_type')
        batch_op.drop_column('sex')

    # ### end Alembic commands ###
