"""empty message

Revision ID: 905f588641b1
Revises: 72fa6a192b69
Create Date: 2024-02-04 11:59:09.662389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905f588641b1'
down_revision = '72fa6a192b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_branch_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.create_foreign_key('fk_address_to_laboratory_branch', 'laboratory_branch', ['lab_branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint('fk_address_to_laboratory_branch', type_='foreignkey')
        batch_op.drop_column('address')
        batch_op.drop_column('lab_branch_id')

    # ### end Alembic commands ###
