"""empty message

Revision ID: aea3fba6e77d
Revises: 
Create Date: 2024-02-03 14:08:45.618537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea3fba6e77d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('affiliate_id', sa.String(length=10), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('verify', sa.DateTime(), nullable=True),
    sa.Column('verify_by_admin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affiliate_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
