"""empty message

Revision ID: b351141bdaa3
Revises: 00ef3d5546b2
Create Date: 2024-02-04 13:02:11.167633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b351141bdaa3'
down_revision = '00ef3d5546b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['lab_branch_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
