"""empty message

Revision ID: eb8e866525ab
Revises: aea3fba6e77d
Create Date: 2024-02-03 19:20:09.784859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8e866525ab'
down_revision = 'aea3fba6e77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliated_by', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('location', sa.Text(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('verify_by_admin',
               existing_type=sa.DATETIME(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('verify_by_admin',
               existing_type=sa.Boolean(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('location')
        batch_op.drop_column('affiliated_by')

    # ### end Alembic commands ###
